name: SimpleJigsaw
version: '${version}'
main: com.gmail.necnionch.myplugin.simplejigsaw.bukkit.SimpleJigsawPlugin
api-version: 1.18
depend: [ WorldEdit ]
softdepend: [ MythicMobs ]
authors: [ Necnion8 ]

commands:
  simplejigsaw:
    aliases: [sjigsaw]
    permission: simplejigsaw.command.simplejigsaw

permissions:
  simplejigsaw.debug:
    default: op

  simplejigsaw.spawner.editor:
    default: op
